### ISSUE TITLE
Snappy-java errors on ppc64le in Sqoop

### ISSUE THREAD

**Issue by sonia-garudi** [OpenPOWER-BigData/HDP-sqoop#1]
Failed tests:
com.cloudera.sqoop.TestParquetImport -
       testSnappyCompression  Failure during job; return status 1
       testNonIdentCharactersInColumnName Failure during job; return status 1
       testFirstUnderscoreInColumnName Failure during job; return status 1
       testNullableParquetImport Failure during job; return status 1
       testOverrideTypeMapping Failure during job; return status 1

com.cloudera.sqoop.TestParquetExport -
       testParquetRecordsNotSupported [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found                                       for os.name=Linux and os.arch=ppc64le
       testMissingParquetFields Could not initialize class org.xerial.snappy.Snappy
       testMissingDatabaseFields Could not initialize class org.xerial.snappy.Snappy
       testNullableField Could not initialize class org.xerial.snappy.Snappy
       testSupportedParquetTypes Could not initialize class org.xerial.snappy.Snappy

com.cloudera.sqoop.hive.TestHiveImport -
       testNormalHiveImportAsParquet Failure during job; return status 1

RCA: 
Sqoop downloads snappy-java 1.0.5 jar which doesn't have ppc support.

**Comment by yussufsh** [comment]
work around is to add snappy-java:1.1.1 dependency to ivy.xml
